# Generated by Django 5.1.1 on 2024-10-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
